controller_configuration:
  - group_name: larm
    controller_name: /larm_controller
    joint_list:
      - l_arm_shy
      - l_arm_shx
      - l_arm_ely
      - l_arm_elx
      - l_arm_wry
      - l_arm_wrx
  - group_name: rarm
    controller_name: /rarm_controller
    joint_list:
      - r_arm_shy
      - r_arm_shx
      - r_arm_ely
      - r_arm_elx
      - r_arm_wry
      - r_arm_wrx
  - group_name: lleg
    controller_name: /lleg_controller
    joint_list:
      - l_leg_hpz
      - l_leg_hpx
      - l_leg_hpy
      - l_leg_kny
      - l_leg_aky
      - l_leg_akx
  - group_name: rleg
    controller_name: /rleg_controller
    joint_list:
      - r_leg_hpz
      - r_leg_hpx
      - r_leg_hpy
      - r_leg_kny
      - r_leg_aky
      - r_leg_akx
  - group_name: torso
    controller_name: /torso_controller
    joint_list:
      - back_bkz
      - back_bky
      - back_bkx
  - group_name: head
    controller_name: /head_controller
    joint_list:
      - neck_ry
