hrpsys_gazebo_configuration:
## velocity feedback for joint control, use parameter gains/joint_name/p_v
  use_velocity_feedback: true
## synchronized hrpsys and gazebo
# use_synchronized_command: false
# name of robot (using for namespace)
  robotname: HRP3HAND_R
# joint_id (order) conversion from gazebo to hrpsys, joint_id_list[gazebo_id] := hrpsys_id
  joint_id_list: [0, 1, 2, 3, 4, 5]
# joints list used in gazebo, sizeof(joint_id_list) == sizeof(joints)
  joints:
    - R_THUMBCM_Y
    - R_THUMBCM_P
    - R_INDEXMP_R
    - R_INDEXMP_P
    - R_INDEXPIP_R
    - R_MIDDLEPIP_R
## jointid:
  gains:
    R_INDEXMP_R: {p: 700.0, d:   0.075, i: 0.0, i_clamp: 0.0, p_v: 10.0}
    R_INDEXMP_P: {p: 700.0, d:   0.075, i: 0.0, i_clamp: 0.0, p_v: 10.0}
    R_INDEXPIP_R: {p: 700.0, d:   0.075, i: 0.0, i_clamp: 0.0, p_v: 10.0}
    R_MIDDLEPIP_R: {p: 700.0, d:   0.075, i: 0.0, i_clamp: 0.0, p_v: 10.0}
    R_THUMBCM_Y: {p: 700.0, d:   0.075, i: 0.0, i_clamp: 0.0, p_v: 10.0}
    R_THUMBCM_P: {p: 700.0, d:   0.075, i: 0.0, i_clamp: 0.0, p_v: 10.0}
